# Generated by Django 5.0.7 on 2024-07-28 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Plant', max_length=100)),
                ('sun_exposure', models.CharField(default='Unknown', max_length=100)),
                ('water_requirements', models.CharField(default='Unknown', max_length=100)),
                ('growth_habit', models.CharField(default='Unknown', max_length=100)),
                ('care_instructions', models.TextField(default='No instructions available.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_text', models.TextField(default='No entry text available.')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('nitrogen_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('phosphorus_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('potassium_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('organic_matter', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('soil_texture', models.CharField(default='Unknown', max_length=100)),
                ('preferred_plants', models.ManyToManyField(to='plants.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(default='User', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
